### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by enragedginger** [ymilky/franzy#6]
It looks like there hasn't been any activity on this project for 9 months. Is it dead?

**Comment by hokkaido** [comment]
Interested in this as well, are you looking for contributors?

**Comment by tcoupland** [comment]
Good question, thinking we could do with a kafka client version upgrade.

**Comment by txbm** [comment]
Agree. I'll help. We're using it in production and I think this library was a great idea / very well written so far. TODOs / contribution roadmap would be awesome and I'll jump in. @ymilky

**Comment by tcoupland** [comment]
I've done some internet stalking and I think @ymilky has moved on. A flurry of activity around this project, both here, on reddit and the slack early last year, but nothing since.

I'm going to move to @lbradstreet fork, he's bumped the version and fixed a little bug. If we need to put more into it at some point then another fork might be made.

**Comment by tcoupland** [comment]
Encountered a small bug with the upgrade, so while acknowledging the risk of over forking, we've created our own branch: https://github.com/MastodonC/franzy

**Comment by chrisbetz** [comment]
I was looking for a version to fulfill two (more) aspects:

* a version to use the latest Kafka 0.11.0.0
* continuous integration, so I could see what’s working and what’s broken at a glance.

So I took input from MastodonC, moved all the different franzy-* projects in a monorepository, added TravisCI builds, updated things and here you are:

Github: https://github.com/clj-kafka/franzy
Clojars: https://clojars.org/search?q=clj-kafka%2Ffranzy
Travis CI: https://travis-ci.org/clj-kafka/franzy

There's still some way to go to update documentation and stuff, but the code is fine, the build is working and you're good to go.

**Comment by enragedginger** [comment]
Thank you, @chrisbetz

**Comment by lbradstreet** [comment]
@chrisbetz thanks for picking this up for kafka 0.11.
